### ISSUE TITLE
wrong solution in the following case

### ISSUE THREAD

**Issue by yuanyelele** [MichaelStott/SimplexSolver#3]
python simplex.py -A "[[1,0,0,1], [1,0,1,0], [0,0,1,1], [0,1,1,0], [0,1,0,1], [1,1,0,0]]" -b "[3,3,2,4,1,3]" -c "[1,1,1,1]"
gives x = [3, 0, 2, 0]
but x[0] + x[3] = 5 > 3

**Comment by MichaelStott** [comment]
The slack variable (s2)  for that equation is equal to -2. (5 -2 = 3). This should be correct.

**Comment by MichaelStott** [comment]
Closing for now, but let me know if you still have any issues.

**Comment by yuanyelele** [comment]
But shouldn't all slack variables be non negtive?

**Comment by LipeAma** [comment]
I'm having the same problem. The slack variables should always be non-negative, otherwise the constraint associated with that variable is being violated.

**Comment by LipeAma** [comment]
Consider the following example

python simplex.py -A "[[-1,-1],[-1,1],[1,2]]" -b "[-3,-1,2]" -c "[1,3]" -p max

The polyhedron generated by these hyperplanes is entirely contained in the 4th quadrant, therefore there is no non-negative solution, and the problem is infeasible. However, the solution given by the script is (4/3, 1/3), which is clearly wrong. And the fact that s1=−4/3, which is negative, indicates that the first constraint is being violated.
